server:
  shutdown: graceful

spring:
  application.name: avengers
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
